// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsW6kCkfedLpSOQfU0KFUxNrkKlV_a7ls',
    appId: '1:67968432515:web:09aa94936044b834cf1eb6',
    messagingSenderId: '67968432515',
    projectId: 'authtutorial-64e99',
    authDomain: 'authtutorial-64e99.firebaseapp.com',
    storageBucket: 'authtutorial-64e99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoDS64NbMdLbFztxTgq9Bnn6sOll3utA0',
    appId: '1:67968432515:android:3d72d7b6f9ec279bcf1eb6',
    messagingSenderId: '67968432515',
    projectId: 'authtutorial-64e99',
    storageBucket: 'authtutorial-64e99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_J7zDEOnqwNqiTgy8r20mvzP7Jrmi4T4',
    appId: '1:67968432515:ios:11971e0f7ef4bb10cf1eb6',
    messagingSenderId: '67968432515',
    projectId: 'authtutorial-64e99',
    storageBucket: 'authtutorial-64e99.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_J7zDEOnqwNqiTgy8r20mvzP7Jrmi4T4',
    appId: '1:67968432515:ios:de1b49bc64dbb2f9cf1eb6',
    messagingSenderId: '67968432515',
    projectId: 'authtutorial-64e99',
    storageBucket: 'authtutorial-64e99.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
